version: "1"
services:
  - type: web
    name: sda-calc-api
    runtime: docker
    repo: https://github.com/stu2454/SDACalc
    plan: free
    region: singapore
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sda-calc-db
          property: connectionString

  - type: web
    name: sda-calc-web
    runtime: docker
    repo: https://github.com/stu2454/SDACalc
    plan: free
    region: singapore
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://sda-calc-api.onrender.com

databases:
  - name: sda-calc-db
    plan: free
    region: singapore
